####################################################################################################
#
# Commands
# [MESSAGE] Send text to player
# [PLAYER] Execute command on behalf of the player
# [CONSOLE] Run command on behalf of console
# [ACTIONBAR] Send text to player in actionbar
# [SOUND] Play a sound for the player
# [EFFECT] Give the player an effect
# [TITLE] Send the player a title, to send a subtitle use the symbol ";"
## For example: [TITLE] First;Second
#
####################################################################################################
#
# Placeholders
# %tend_top_<число>% - Показывает то что в строке placeholder-top-format
# %tend_top_<число>_coordinates% - Показывает координаты нужного топа
# %tend_top_<число>_amount% - Показывает кол-во яиц нужного топа
# %tend_damage_top_<число>_name% - Показывает ник игрока нужного топа по урону дракона
# %tend_damage_top_<число>_damage% - Показывает урон нужного топа по урону дракона
# %tend_scheduler_time_to_start%
# %tend_scheduler_time_to_start_string%
# %tend_scheduler_time_to_end%
# %tend_scheduler_time_to_end_string%
#
####################################################################################################

storage:
  type: YAML # SQLITE, MYSQL, YAML
  # данные ниже нужны если у вас type стоит на MYSQL
  host: "localhost"
  port: 3306
  database: "treexend"
  username: "root"
  password: ""

listeners:
  dropOnQuit: true # Дропнуть на землю если игрок вышел с сервера
  place: false # Может ли игрок поставить яйцо
  glowOnDrop: true # подсвечивает яйцо если оно валяется на земле
  teleportOnPortalJoin: false # телепортировать ли игрока на координаты из end-enter-teleport

end-enter-teleport: 0;100;0;world # локацию куда телепортирует игроков, которые войдут в энде. Нужен teleportOnPortalJoin: true
end-close-teleport: 0;100;0;world # локацию куда телепортирует игроков, которые находятся в энде.

trade-command: "egg-swap" # Команда на обмен яиц

placeholder-top-format: "&dx: %x%, y: %y%, z: %z% (%amount%) &7шт"

dragon-egg:
  name: "&#FB0783Яйцо дракона"
  glowing: false
  lore:
    - ""
    - "&#FB0783&n◢&f В ваших руках самый ценный предмет."
    - "&#FB0783◤&f Будьте с ним осторожнее!"
    - ""
    - "&#FB43F9Вот его особенности:"
    - "&#FB0783● &fВ конце вайпа яйцо(а) можно"
    - "  &fобменять на Сапфиры - &#FB0783/egg-swap"
    - "  &fКурс обмена: &#FB07831 яйцо &f= &#FB07832500 сапфиров"
    - "&#FB0783● &fПрятать яйца можно только"
    - "&#FB0783  в обычном сундуке."
    - "&#FB0783● &fНа спавне формируется топ,"
    - "  &fпо спрятанным яйцам - &#FB0783/warp top"
    - ""
  prizes:
    # Чтобы использовать математические символы, вам надо писать в скобках например: {10*10}
    # Команда на получение награды /egg-swap
    - "[CONSOLE] p give %player% {2500*%eggs_amount%}"
    - "[MESSAGE] "
    - "[MESSAGE] &aПоздравляем"
    - "[MESSAGE] &fВ получили &a{2500*%eggs_amount%} токенов."
    - "[MESSAGE] "

messages:
  dragonDamage:
    messageDelay: 60 # В секундах. Каждые 60 секунд все увидят это сообщение, до тех пор пока дракон жив.
    message:
      - ""
      - "Могущественный Дракон &#d27c33скоро будет поврежен, &fи всё"
      - "благодаря этим воинам:"
      - "&#ebcd35▪ 1 место &7- &#3dcde0%tend_damage_top_1_name% &7| &#d27c33%tend_damage_top_1_damage%"
      - "&f▪ 2 место &7- &#3dcde0%tend_damage_top_2_name% &7| &#d27c33%tend_damage_top_2_damage%"
      - "&#d27c33▪ 3 место &7- &#3dcde0%tend_damage_top_3_name% &7| &#d27c33%tend_damage_top_3_damage%"
      - ""
      - "Игрок, занявший первое место, &#ebcd35&lполучит Яйцо дракона."
      - ""
  endIsClose:
    - "&fЭндер мир сейчас закрыт, возвращайтесь в &bвоскресенье в 16:00 &fпо МСК"
  tradingIsDisabled:
    - "&cСейчас вы не можете обменять яйца."
  noEggs:
    - "&cУ вас нету яиц дракона для получения приза!"
  chestOnly:
    - "Яйцо Дракона можно хранить только в сундуке."
  portalIsBlocked:
    - "&b▶ &fВ настоящий момент измерение закрыто."
    - "&b Приходи в воскресенье в 16:00"

BossBar:
  duration:
    enable: false
    title: "Энд закроется через %tend_scheduler_time_to_end% сек."
    Color: RED
    Style: SOLID
  egg:
    enable: true
    title: "Осторожно у вас в инвентаре яйцо дракона"
    Color: RED
    Style: SOLID


# Ниже настройки плейсхолдера %tend_scheduler_time_to_start_string% и остальные string

formattedTime:
  format: "%weeks% %days% %hours% %minutes% %seconds%"
  seconds:
    - 'секунду'
    - 'секунды'
    - 'секунд'
  minutes:
    - 'минуту'
    - 'минуты'
    - 'минут'
  hours:
    - 'час'
    - 'часа'
    - 'часов'
  days:
    - 'день'
    - 'дня'
    - 'дней'
  weeks:
    - 'неделю'
    - 'недели'
    - 'недель'
