name: TreexEnd
version: '${project.version}'
main: me.jetby.treexend.Main
api-version: '1.16'
author: MrJetby
website: https://treexstudio.pro
depend:
  - PlaceholderAPI
commands:
  tend:
    aliases:
      - treexend